//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatluongcomputer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingCode
    {
        public int TrackingId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Carrier { get; set; }
        public string TrackingNumber { get; set; }
        public string Status { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
